import type { MockExam, QuizQuestion } from "./quiz-data";

const q = (id: number, topic: string, prompt: string, support: string, correct: string, options: QuizQuestion["options"]): QuizQuestion => ({ id, topic, prompt, support, correct, options });

export const mathQuizQuestions: QuizQuestion[] = [
  q(101,"Números negativos","Quanto é −7 + (−5)?","Sinais iguais na adição: some os módulos e mantenha o sinal.","b",[
    {id:"a",label:"2",explanation:"Você subtraiu 7 − 5, mas os dois números têm o mesmo sinal."},{id:"b",label:"−12",explanation:"Correto. Some 7 + 5 = 12 e mantenha o sinal negativo."},{id:"c",label:"12",explanation:"O módulo está certo, mas faltou manter o sinal negativo."},{id:"d",label:"−2",explanation:"Subtrair os módulos só vale quando os sinais são diferentes."}]),
  q(102,"Números negativos","Quanto é −9 + 14?","Sinais diferentes: subtraia os módulos e use o sinal do maior módulo.","c",[
    {id:"a",label:"−23",explanation:"Você somou os módulos e manteve o negativo, regra usada apenas para sinais iguais."},{id:"b",label:"−5",explanation:"9 e 14 dão diferença 5, mas o maior módulo é 14, que é positivo."},{id:"c",label:"5",explanation:"Correto. 14 − 9 = 5 e o maior módulo pertence ao número positivo."},{id:"d",label:"23",explanation:"Somar 9 + 14 ignora que os sinais são diferentes."}]),
  q(103,"Números negativos","Quanto é 6 − (−8)?","Subtrair um número é somar o oposto dele.","d",[
    {id:"a",label:"−2",explanation:"Você fez 6 − 8 e ignorou que o número subtraído já era negativo."},{id:"b",label:"2",explanation:"A distância entre 6 e 8 não é a operação pedida."},{id:"c",label:"−14",explanation:"O segundo sinal muda: subtrair −8 vira somar +8."},{id:"d",label:"14",explanation:"Correto. 6 − (−8) = 6 + 8 = 14."}]),
  q(104,"Números negativos","Quanto é −4 − 7?","Reescreva como −4 + (−7).","a",[
    {id:"a",label:"−11",explanation:"Correto. −4 − 7 = −4 + (−7); sinais iguais, some e mantenha o negativo."},{id:"b",label:"−3",explanation:"Você calculou 7 − 4, mas partir de −4 e andar 7 para a esquerda chega a −11."},{id:"c",label:"3",explanation:"A resposta positiva não combina com dois deslocamentos para o lado negativo."},{id:"d",label:"11",explanation:"O módulo é 11, mas o resultado deve ser negativo."}]),
  q(105,"Regras de sinais","Calcule: (−6) × (−3).","Na multiplicação, sinais iguais dão resultado positivo.","c",[
    {id:"a",label:"−18",explanation:"O produto 6 × 3 é 18, mas negativo vezes negativo dá positivo."},{id:"b",label:"−9",explanation:"Você somou os números; a operação é multiplicação."},{id:"c",label:"18",explanation:"Correto. 6 × 3 = 18 e sinais iguais dão +."},{id:"d",label:"9",explanation:"A regra de sinais está positiva, mas 6 × 3 não é 9."}]),
  q(106,"Regras de sinais","Calcule: 48 ÷ (−6).","Na divisão, sinais diferentes dão resultado negativo.","b",[
    {id:"a",label:"8",explanation:"48 ÷ 6 = 8, mas sinais diferentes tornam o resultado negativo."},{id:"b",label:"−8",explanation:"Correto. 48 ÷ 6 = 8 e + dividido por − dá −."},{id:"c",label:"−42",explanation:"Você parece ter subtraído 6 de 48 em vez de dividir."},{id:"d",label:"42",explanation:"A operação correta é divisão, não subtração."}]),
  q(107,"Módulo e oposto","Qual é o oposto de −12?","O oposto fica à mesma distância do zero, do outro lado.","a",[
    {id:"a",label:"12",explanation:"Correto. −12 e 12 são simétricos em relação ao zero."},{id:"b",label:"−12",explanation:"Esse é o próprio número, não o oposto."},{id:"c",label:"0",explanation:"Somar um número ao seu oposto dá zero, mas zero não é o oposto de −12."},{id:"d",label:"1/12",explanation:"Isso é o inverso multiplicativo de 12, não o oposto."}]),
  q(108,"Módulo e oposto","Qual afirmação é verdadeira?","Módulo é a distância até o zero e nunca é negativo.","d",[
    {id:"a",label:"|−9| = −9",explanation:"Distância não tem sinal negativo: |−9| = 9."},{id:"b",label:"O oposto de 5 é 5",explanation:"O oposto de 5 é −5."},{id:"c",label:"−2 é maior que 1",explanation:"Na reta, −2 fica à esquerda de 1, portanto é menor."},{id:"d",label:"|−9| = 9",explanation:"Correto. −9 está a 9 unidades do zero."}]),
  q(109,"Parênteses","Calcule: 3 + (8 − 11).","Resolva o parêntese antes da soma externa.","c",[
    {id:"a",label:"16",explanation:"Você provavelmente somou 3 + 8 + 11 e perdeu o sinal de subtração."},{id:"b",label:"−6",explanation:"8 − 11 = −3; depois ainda é preciso somar 3."},{id:"c",label:"0",explanation:"Correto. 8 − 11 = −3 e 3 + (−3) = 0."},{id:"d",label:"6",explanation:"O parêntese vale −3, não +3."}]),
  q(110,"Parênteses","Calcule: 15 − (4 + 7).","O parêntese inteiro vale 11.","a",[
    {id:"a",label:"4",explanation:"Correto. 4 + 7 = 11; então 15 − 11 = 4."},{id:"b",label:"18",explanation:"Você fez 15 − 4 + 7, retirando o parêntese sem distribuir o sinal de menos."},{id:"c",label:"26",explanation:"Você somou todos os termos, mas há uma subtração antes do parêntese."},{id:"d",label:"−4",explanation:"15 é maior que 11; a diferença é positiva."}]),
  q(111,"Parênteses","Calcule: −(6 − 10).","Resolva dentro primeiro ou troque todos os sinais ao retirar o parêntese.","b",[
    {id:"a",label:"−16",explanation:"Você somou 6 e 10 e manteve o negativo; dentro há uma subtração."},{id:"b",label:"4",explanation:"Correto. 6 − 10 = −4 e o oposto de −4 é +4."},{id:"c",label:"−4",explanation:"Esse é o valor dentro do parêntese; ainda falta aplicar o sinal de menos de fora."},{id:"d",label:"16",explanation:"O módulo interno é 4, não 16."}]),
  q(112,"Parênteses","Qual expressão é equivalente a −(x − 5)?","O sinal de menos antes do parêntese troca todos os sinais internos.","d",[
    {id:"a",label:"−x − 5",explanation:"O sinal de x mudou, mas o de −5 também precisa mudar."},{id:"b",label:"x − 5",explanation:"O sinal externo não pode simplesmente desaparecer."},{id:"c",label:"x + 5",explanation:"Você trocou apenas o sinal do 5 e manteve x positivo."},{id:"d",label:"−x + 5",explanation:"Correto. Distribuir −1 em x − 5 resulta em −x + 5."}]),
  q(113,"Ordem das operações","Calcule: 5 + 3 × 4.","Multiplicação vem antes da adição.","c",[
    {id:"a",label:"32",explanation:"Você fez 5 + 3 primeiro. Sem parênteses, a multiplicação vem antes."},{id:"b",label:"27",explanation:"Nenhuma etapa correta produz 27."},{id:"c",label:"17",explanation:"Correto. 3 × 4 = 12; depois 5 + 12 = 17."},{id:"d",label:"20",explanation:"Você pode ter multiplicado 5 × 4 e ignorado o 3."}]),
  q(114,"Ordem das operações","Calcule: (5 + 3) × 4.","Agora o parêntese muda a ordem.","a",[
    {id:"a",label:"32",explanation:"Correto. 5 + 3 = 8; depois 8 × 4 = 32."},{id:"b",label:"17",explanation:"Esse seria o resultado de 5 + 3 × 4 sem parênteses."},{id:"c",label:"20",explanation:"Você multiplicou 5 × 4 e perdeu o 3."},{id:"d",label:"12",explanation:"Você somou 5 + 3 + 4, mas a operação externa é multiplicação."}]),
  q(115,"Ordem das operações","Calcule: 24 ÷ 6 × 2.","Multiplicação e divisão têm a mesma prioridade: faça da esquerda para a direita.","d",[
    {id:"a",label:"2",explanation:"Você fez 6 × 2 primeiro, mas operações do mesmo nível seguem da esquerda para a direita."},{id:"b",label:"4",explanation:"Esse é apenas o resultado da primeira etapa; ainda falta × 2."},{id:"c",label:"12",explanation:"Você pode ter dividido 24 por 2 e ignorado a ordem."},{id:"d",label:"8",explanation:"Correto. 24 ÷ 6 = 4; depois 4 × 2 = 8."}]),
  q(116,"Ordem das operações","Calcule: 20 − 2 × (3 + 4).","Parênteses primeiro; multiplicação depois; subtração por último.","b",[
    {id:"a",label:"126",explanation:"Você parece ter feito 20 − 2 antes e multiplicado por 7."},{id:"b",label:"6",explanation:"Correto. (3 + 4)=7; 2×7=14; 20−14=6."},{id:"c",label:"18",explanation:"Você fez 20 − 2 e não aplicou a multiplicação pelo parêntese."},{id:"d",label:"12",explanation:"Revise as etapas: 2 × 7 é 14, não 8."}]),
  q(117,"Ordem das operações","Calcule: −3 + 2 × (−5).","Multiplique antes de somar.","c",[
    {id:"a",label:"−5",explanation:"Você somou −3 + 2 primeiro; a multiplicação tem prioridade."},{id:"b",label:"7",explanation:"2 × (−5) é negativo, não positivo."},{id:"c",label:"−13",explanation:"Correto. 2×(−5)=−10; então −3+(−10)=−13."},{id:"d",label:"13",explanation:"O módulo é 13, mas a soma de dois negativos permanece negativa."}]),
  q(118,"Potências e sinais","Calcule: (−4)².","Os parênteses mostram que a base inteira é −4.","a",[
    {id:"a",label:"16",explanation:"Correto. (−4)×(−4)=+16."},{id:"b",label:"−16",explanation:"Negativo vezes negativo dá positivo quando o sinal faz parte da base."},{id:"c",label:"−8",explanation:"Potência não significa multiplicar a base pelo expoente."},{id:"d",label:"8",explanation:"4² é 4×4=16, não 4×2."}]),
  q(119,"Potências e sinais","Calcule: −4².","Sem parênteses, a potência vale para o 4; o sinal de menos fica fora.","b",[
    {id:"a",label:"16",explanation:"Isso seria (−4)², com o negativo dentro de parênteses."},{id:"b",label:"−16",explanation:"Correto. Primeiro 4²=16; depois aplique o sinal de menos: −16."},{id:"c",label:"−8",explanation:"Potência não é base vezes expoente."},{id:"d",label:"8",explanation:"4² vale 16, não 8."}]),
  q(120,"Expressões algébricas","Se x = −3, quanto vale 2x + 5?","Substitua x usando parênteses: 2(−3)+5.","d",[
    {id:"a",label:"11",explanation:"Você tratou x como +3; preserve o sinal ao substituir."},{id:"b",label:"−11",explanation:"2(−3)=−6, mas −6+5 é −1."},{id:"c",label:"1",explanation:"A diferença é 1, mas o maior módulo na soma é 6, negativo."},{id:"d",label:"−1",explanation:"Correto. 2(−3)=−6 e −6+5=−1."}]),
  q(121,"Expressões algébricas","Se a = −2 e b = 4, quanto vale 3a − b?","Substitua com parênteses: 3(−2) − 4.","a",[
    {id:"a",label:"−10",explanation:"Correto. 3(−2)=−6 e −6−4=−10."},{id:"b",label:"−2",explanation:"Você pode ter feito −6+4; a expressão pede subtrair b."},{id:"c",label:"2",explanation:"O resultado não pode ser positivo: começamos em −6 e subtraímos 4."},{id:"d",label:"10",explanation:"O módulo é 10, mas os dois movimentos são negativos."}]),
  q(122,"Expressões algébricas","Qual expressão representa “o dobro de um número, menos 7”?","Use x para representar o número.","c",[
    {id:"a",label:"2(x − 7)",explanation:"Isso representa o dobro da diferença entre o número e 7."},{id:"b",label:"x − 14",explanation:"Isso subtrai o dobro de 7, mas não dobra o número."},{id:"c",label:"2x − 7",explanation:"Correto. O dobro do número é 2x; depois retiramos 7."},{id:"d",label:"7 − 2x",explanation:"A ordem foi invertida: isso é 7 menos o dobro do número."}]),
  q(123,"Distributiva","Simplifique: 3(x + 4).","Multiplique 3 por cada termo dentro do parêntese.","b",[
    {id:"a",label:"3x + 4",explanation:"Você distribuiu o 3 apenas para x; ele também multiplica o 4."},{id:"b",label:"3x + 12",explanation:"Correto. 3·x + 3·4 = 3x + 12."},{id:"c",label:"7x",explanation:"x e 4 não são termos semelhantes e não podem virar 5x antes da multiplicação."},{id:"d",label:"12x",explanation:"3×4=12, mas o x pertence apenas ao primeiro termo."}]),
  q(124,"Distributiva","Simplifique: −2(x − 5).","Distribua −2 para os dois termos e cuide dos sinais.","d",[
    {id:"a",label:"−2x − 10",explanation:"−2×(−5) é +10, não −10."},{id:"b",label:"2x − 10",explanation:"−2×x é −2x; o sinal do primeiro termo mudou errado."},{id:"c",label:"−2x + 5",explanation:"Você não multiplicou o 5 por 2."},{id:"d",label:"−2x + 10",explanation:"Correto. −2·x=−2x e −2·(−5)=+10."}]),
  q(125,"Expressão mista","Calcule: 18 − 2 × (5 − 8).","Faça parênteses, multiplicação e, por fim, a subtração do número negativo.","c",[
    {id:"a",label:"12",explanation:"Você pode ter usado 5−8 como +3; na verdade é −3."},{id:"b",label:"−24",explanation:"O valor numérico correto é positivo; revise 18−(−6)."},{id:"c",label:"24",explanation:"Correto. (5−8)=−3; 2×(−3)=−6; 18−(−6)=24."},{id:"d",label:"−12",explanation:"Subtrair −6 significa somar 6, então o resultado não é negativo."}]),
  q(126,"Expressão mista","Calcule: −3[2 − (−4)].","Resolva o parêntese interno antes da multiplicação externa.","a",[
    {id:"a",label:"−18",explanation:"Correto. 2−(−4)=6 e −3×6=−18."},{id:"b",label:"18",explanation:"−3×6 tem sinais diferentes e, por isso, é negativo."},{id:"c",label:"6",explanation:"Esse é apenas o valor dentro do colchete; ainda falta multiplicar por −3."},{id:"d",label:"−6",explanation:"Você pode ter feito 2−4, mas subtrair −4 vira somar 4."}]),
  q(127,"Expressão mista","Calcule: 30 ÷ [2 × (−3 + 8)].","Comece pelo parêntese, depois resolva o colchete.","b",[
    {id:"a",label:"75",explanation:"Você não deve dividir 30 por 2 antes de concluir todo o denominador no colchete."},{id:"b",label:"3",explanation:"Correto. (−3+8)=5; 2×5=10; 30÷10=3."},{id:"c",label:"15",explanation:"Isso é 30÷2; ainda faltaria considerar o fator 5."},{id:"d",label:"−3",explanation:"O parêntese vale +5, então o divisor e o resultado são positivos."}]),
  q(128,"Estratégia","Qual é o primeiro passo em 12 − 3 × (−2 + 6)?","Procure o agrupamento mais interno antes de calcular.","d",[
    {id:"a",label:"Fazer 12 − 3",explanation:"A leitura da esquerda para a direita não vence a prioridade dos parênteses."},{id:"b",label:"Fazer 3 × (−2)",explanation:"Não se distribui parcialmente quando é possível resolver o parêntese inteiro primeiro."},{id:"c",label:"Trocar todos os sinais",explanation:"Não há um sinal de menos diretamente distribuindo o parêntese."},{id:"d",label:"Calcular −2 + 6",explanation:"Correto. O parêntese é o nível mais interno e vale 4."}]),
  q(129,"Equação · uma etapa","Resolva: x + 8 = 21.","Desfaça +8 com −8 nos dois lados.","b",[
    {id:"a",label:"x = 29",explanation:"Você somou 8, mas precisa desfazer a soma usando a operação inversa."},{id:"b",label:"x = 13",explanation:"Correto. x=21−8=13; conferindo: 13+8=21."},{id:"c",label:"x = −13",explanation:"A subtração 21−8 é positiva."},{id:"d",label:"x = 168",explanation:"Multiplicar 21 por 8 não desfaz a soma."}]),
  q(130,"Equação · uma etapa","Resolva: x − 11 = −4.","Some 11 aos dois lados para deixar x sozinho.","c",[
    {id:"a",label:"x = −15",explanation:"Você subtraiu 11 outra vez; a operação inversa de −11 é +11."},{id:"b",label:"x = 15",explanation:"O sinal foi perdido: −4+11=7."},{id:"c",label:"x = 7",explanation:"Correto. x=−4+11=7; 7−11=−4."},{id:"d",label:"x = −7",explanation:"A diferença tem módulo 7, mas 11 é o número de maior módulo e é positivo."}]),
  q(131,"Equação · multiplicação","Resolva: 5x = −35.","Divida os dois lados por 5.","a",[
    {id:"a",label:"x = −7",explanation:"Correto. −35÷5=−7 e 5(−7)=−35."},{id:"b",label:"x = 7",explanation:"Positivo vezes positivo não produziria −35."},{id:"c",label:"x = −30",explanation:"5x é multiplicação; subtrair 5 não isola x."},{id:"d",label:"x = −175",explanation:"Você multiplicou quando precisava desfazer a multiplicação dividindo."}]),
  q(132,"Equação · divisão","Resolva: x ÷ 6 = −3.","Multiplique os dois lados por 6.","d",[
    {id:"a",label:"x = −1/2",explanation:"Você dividiu −3 por 6, repetindo a operação em vez de desfazê-la."},{id:"b",label:"x = 2",explanation:"O sinal e a operação não foram preservados."},{id:"c",label:"x = 18",explanation:"O módulo está certo, mas −3×6 é negativo."},{id:"d",label:"x = −18",explanation:"Correto. x=−3×6=−18; −18÷6=−3."}]),
  q(133,"Equação · duas etapas","Resolva: 2x + 5 = 19.","Primeiro desfaça +5; depois desfaça ×2.","c",[
    {id:"a",label:"x = 12",explanation:"19−5=14, não 12, e ainda é preciso dividir por 2."},{id:"b",label:"x = 8",explanation:"Se x=8, 2x+5=21; confira sempre na equação original."},{id:"c",label:"x = 7",explanation:"Correto. 2x=14 e x=7; 2(7)+5=19."},{id:"d",label:"x = 28",explanation:"Você multiplicou por 2 quando precisava dividir."}]),
  q(134,"Equação · duas etapas","Resolva: −3x − 4 = 17.","Some 4 nos dois lados; depois divida por −3.","b",[
    {id:"a",label:"x = 7",explanation:"21÷3=7, mas o coeficiente de x é −3."},{id:"b",label:"x = −7",explanation:"Correto. −3x=21; x=21÷(−3)=−7."},{id:"c",label:"x = −13/3",explanation:"Você pode ter subtraído 4 de 17; para desfazer −4, some 4."},{id:"d",label:"x = −21",explanation:"Ainda faltou dividir o coeficiente −3."}]),
  q(135,"Equação · x nos dois lados","Resolva: 5x + 2 = 3x + 14.","Leve os termos com x para um lado e os números para o outro.","a",[
    {id:"a",label:"x = 6",explanation:"Correto. 5x−3x=14−2; 2x=12; x=6."},{id:"b",label:"x = 8",explanation:"Você subtraiu apenas os números e esqueceu de reduzir 5x−3x."},{id:"c",label:"x = −6",explanation:"Com x=−6, os dois lados não ficam iguais."},{id:"d",label:"x = 16",explanation:"Somar os números não mantém a igualdade organizada."}]),
  q(136,"Equação · x nos dois lados","Resolva: 4x − 9 = 7x + 3.","Subtraia 4x dos dois lados e depois subtraia 3.","d",[
    {id:"a",label:"x = 4",explanation:"O resultado tem sinal negativo: −12=3x."},{id:"b",label:"x = −12",explanation:"Esse é o valor de 3x, não de x."},{id:"c",label:"x = 12",explanation:"Você perdeu o sinal ao mover os termos."},{id:"d",label:"x = −4",explanation:"Correto. −12=3x; x=−4. Os dois lados valem −25."}]),
  q(137,"Equação · parênteses","Resolva: 3(x + 4) = 27.","Você pode dividir por 3 primeiro ou usar a distributiva.","b",[
    {id:"a",label:"x = 13",explanation:"Você fez 27÷3+4; depois de dividir, é preciso subtrair 4."},{id:"b",label:"x = 5",explanation:"Correto. x+4=9; x=5."},{id:"c",label:"x = 9",explanation:"Esse é o valor de x+4, ainda não de x."},{id:"d",label:"x = 23",explanation:"Subtrair apenas 4 de 27 ignora o fator 3."}]),
  q(138,"Equação · distributiva","Resolva: 2(x − 3) + 4 = 18.","Distribua 2 ou desfaça as operações externas na ordem inversa.","c",[
    {id:"a",label:"x = 5",explanation:"Com x=5, o lado esquerdo vale 8, não 18."},{id:"b",label:"x = 7",explanation:"Você pode ter esquecido o +4 ou distribuído apenas em x."},{id:"c",label:"x = 10",explanation:"Correto. 2x−6+4=18; 2x=20; x=10."},{id:"d",label:"x = 14",explanation:"18−4=14 é apenas uma etapa; ainda há o parêntese multiplicado por 2."}]),
  q(139,"Equação · distributiva","Resolva: −2(x + 1) = 10.","Divida por −2; depois desfaça +1.","a",[
    {id:"a",label:"x = −6",explanation:"Correto. x+1=−5; x=−6."},{id:"b",label:"x = 4",explanation:"10÷(−2)=−5, não +5."},{id:"c",label:"x = −4",explanation:"Se x=−4, −2(x+1)=6."},{id:"d",label:"x = 6",explanation:"O sinal negativo externo precisa ser considerado."}]),
  q(140,"Equação · fração","Resolva: (x + 2) ÷ 4 = 3.","Multiplique os dois lados por 4; depois subtraia 2.","d",[
    {id:"a",label:"x = 1/4",explanation:"Você dividiu outra vez em vez de desfazer a divisão."},{id:"b",label:"x = 10/4",explanation:"O parêntese inteiro é dividido por 4."},{id:"c",label:"x = 14",explanation:"12 é o valor de x+2; portanto x é 10."},{id:"d",label:"x = 10",explanation:"Correto. x+2=12; x=10."}]),
  q(141,"Equação · fração","Resolva: (2x − 1) ÷ 3 = 5.","Multiplique por 3 antes de trabalhar dentro do numerador.","b",[
    {id:"a",label:"x = 7",explanation:"2(7)−1=13, que dividido por 3 não dá 5."},{id:"b",label:"x = 8",explanation:"Correto. 2x−1=15; 2x=16; x=8."},{id:"c",label:"x = 3",explanation:"Você pode ter feito 5−3+1 sem respeitar a estrutura da fração."},{id:"d",label:"x = 16",explanation:"16 é o valor de 2x; ainda falta dividir por 2."}]),
  q(142,"Equação · potência","Resolva no conjunto dos racionais: x² = 64.","Procure todos os números racionais cujo quadrado é 64.","c",[
    {id:"a",label:"x = 8 apenas",explanation:"8 funciona, mas −8 também, pois negativo vezes negativo é positivo."},{id:"b",label:"x = 32",explanation:"Elevar ao quadrado não significa multiplicar por 2."},{id:"c",label:"x = 8 ou x = −8",explanation:"Correto. 8²=64 e (−8)²=64."},{id:"d",label:"x = 4 ou x = −4",explanation:"4² vale 16, não 64."}]),
  q(143,"Equação · potência","Resolva: (x − 1)² = 25.","Se algo ao quadrado vale 25, esse algo pode ser 5 ou −5.","d",[
    {id:"a",label:"x = 6 apenas",explanation:"x−1=5 dá x=6, mas falta considerar x−1=−5."},{id:"b",label:"x = 26",explanation:"Você somou 1 a 25 sem desfazer o quadrado."},{id:"c",label:"x = 5 ou x = −5",explanation:"Esses são os valores de x−1, não de x."},{id:"d",label:"x = 6 ou x = −4",explanation:"Correto. x−1=5 dá 6; x−1=−5 dá −4."}]),
  q(144,"Equação · potência","Resolva: 2x² = 18.","Primeiro divida por 2; depois resolva x²=9.","a",[
    {id:"a",label:"x = 3 ou x = −3",explanation:"Correto. x²=9 e os dois sinais funcionam."},{id:"b",label:"x = 9",explanation:"9 é o valor de x², não de x."},{id:"c",label:"x = 3 apenas",explanation:"−3 também satisfaz, pois (−3)²=9."},{id:"d",label:"x = 16",explanation:"Subtrair 2 não desfaz a multiplicação por 2."}]),
  q(145,"Equação · raiz","Resolva: √x = 7.","Eleve os dois lados ao quadrado.","b",[
    {id:"a",label:"x = 3,5",explanation:"Dividir 7 por 2 não desfaz uma raiz quadrada."},{id:"b",label:"x = 49",explanation:"Correto. x=7²=49; √49=7."},{id:"c",label:"x = 14",explanation:"Elevar ao quadrado não é multiplicar por 2."},{id:"d",label:"x = ±49",explanation:"x precisa estar no domínio da raiz e √x é não negativa; x=49."}]),
  q(146,"Equação · raiz","Resolva: √(x + 5) = 4.","Eleve ao quadrado: x+5=16.","c",[
    {id:"a",label:"x = −1",explanation:"Você subtraiu 5 de 4 antes de desfazer a raiz."},{id:"b",label:"x = 21",explanation:"Depois de obter 16, é preciso subtrair 5, não somar."},{id:"c",label:"x = 11",explanation:"Correto. x+5=16; x=11; √16=4."},{id:"d",label:"x = 8",explanation:"4×2 não é a operação inversa da raiz."}]),
  q(147,"Princípio da igualdade","Qual ação mantém a igualdade em 3x + 2 = 14?","Pense na equação como uma balança.","a",[
    {id:"a",label:"Subtrair 2 dos dois lados",explanation:"Correto. Fazer a mesma operação nos dois lados preserva a igualdade."},{id:"b",label:"Subtrair 2 apenas do lado esquerdo",explanation:"Isso desequilibra a equação."},{id:"c",label:"Dividir apenas o 3 por 14",explanation:"O lado direito precisa receber a mesma operação aplicada ao lado esquerdo inteiro."},{id:"d",label:"Trocar +2 por −2 sem alterar o outro lado",explanation:"Mover termo é um atalho para operar igualmente nos dois lados, não uma troca mágica de sinal."}]),
  q(148,"Interpretação algébrica","“O triplo de um número, diminuído de 4, é 20.” Qual equação representa a frase?","Traduza cada parte mantendo a ordem: triplo, menos 4, igual a 20.","d",[
    {id:"a",label:"3(x − 4) = 20",explanation:"Isso triplica também o 4: representa o triplo da diferença."},{id:"b",label:"x − 12 = 20",explanation:"O número não foi triplicado."},{id:"c",label:"4 − 3x = 20",explanation:"A ordem foi invertida."},{id:"d",label:"3x − 4 = 20",explanation:"Correto. 3x é o triplo do número; depois diminuímos 4."}]),
  q(149,"Frações equivalentes","Qual fração é equivalente a 3/4?","Multiplique numerador e denominador pelo mesmo número.","b",[
    {id:"a",label:"6/4",explanation:"Você multiplicou apenas o numerador; isso muda o valor."},{id:"b",label:"9/12",explanation:"Correto. 3×3=9 e 4×3=12."},{id:"c",label:"4/3",explanation:"Essa é a fração inversa."},{id:"d",label:"3/8",explanation:"Dobrar só o denominador reduz o valor pela metade."}]),
  q(150,"Operações com racionais","Calcule: 2/3 + 1/6.","Encontre um denominador comum: 2/3 = 4/6.","c",[
    {id:"a",label:"3/9",explanation:"Não se somam os denominadores diretamente."},{id:"b",label:"3/6",explanation:"Você somou os numeradores sem transformar 2/3 em sextos."},{id:"c",label:"5/6",explanation:"Correto. 4/6+1/6=5/6."},{id:"d",label:"1/2",explanation:"1/2=3/6; ainda faltam 2/6."}]),
  q(151,"Operações com racionais","Calcule: (−3/5) × (10/9).","Multiplique e simplifique; sinais diferentes dão negativo.","a",[
    {id:"a",label:"−2/3",explanation:"Correto. −30/45 simplifica para −2/3."},{id:"b",label:"2/3",explanation:"O módulo está certo, mas negativo vezes positivo dá negativo."},{id:"c",label:"−30/14",explanation:"Na multiplicação de frações, multiplique numerador por numerador e denominador por denominador."},{id:"d",label:"7/14",explanation:"Somar termos não corresponde à operação pedida."}]),
  q(152,"Simplificação algébrica","Simplifique: 4x + 3 − 2x + 5.","Junte termos semelhantes: termos com x entre si e constantes entre si.","d",[
    {id:"a",label:"10x",explanation:"3 e 5 não têm x e não podem virar termos com x."},{id:"b",label:"2x + 2",explanation:"4x−2x=2x, mas 3+5=8."},{id:"c",label:"6x + 8",explanation:"O termo −2x deve ser subtraído, não somado."},{id:"d",label:"2x + 8",explanation:"Correto. 4x−2x=2x e 3+5=8."}]),
  q(153,"Termos semelhantes","Quais termos são semelhantes?","A parte literal precisa ser exatamente igual, inclusive os expoentes.","b",[
    {id:"a",label:"3x e 3x²",explanation:"Os expoentes são diferentes: x e x² não têm a mesma parte literal."},{id:"b",label:"−5a² e 8a²",explanation:"Correto. Os coeficientes podem mudar; a parte literal a² é a mesma."},{id:"c",label:"4ab e 4a",explanation:"O primeiro termo também possui b."},{id:"d",label:"7x e 7y",explanation:"As variáveis são diferentes."}]),
  q(154,"Interpretação algébrica","Qual expressão representa “o triplo da soma de um número com 5”?","A expressão x+5 precisa ficar agrupada antes de ser triplicada.","a",[
    {id:"a",label:"3(x + 5)",explanation:"Correto. O triplo multiplica a soma inteira."},{id:"b",label:"3x + 5",explanation:"Isso é a soma do triplo do número com 5."},{id:"c",label:"x + 15",explanation:"Somente o 5 foi triplicado."},{id:"d",label:"3x · 5",explanation:"A frase pede soma, não produto por 5."}]),
  q(155,"Problema · idades","Pedro e Paulo somam 34 anos. Pedro tem 2 anos a mais. Se Paulo tem x anos, qual equação modela a situação?","Pedro=x+2 e Paulo=x; a soma dos dois é 34.","c",[
    {id:"a",label:"x + 2 = 34",explanation:"A idade de Paulo não foi somada."},{id:"b",label:"2x = 34",explanation:"As idades não são iguais; diferem em 2."},{id:"c",label:"x + (x + 2) = 34",explanation:"Correto. Somamos Paulo e Pedro."},{id:"d",label:"x − (x + 2) = 34",explanation:"O enunciado informa uma soma."}]),
  q(156,"Problema · perímetro","A altura de um retângulo é x, a base é x+1 e o perímetro é 14 cm. Qual equação usar?","Perímetro é a soma dos quatro lados.","d",[
    {id:"a",label:"x(x + 1) = 14",explanation:"Isso calcula a área."},{id:"b",label:"x + x + 1 = 14",explanation:"Foram contados apenas dois lados."},{id:"c",label:"2x(x + 1) = 14",explanation:"O perímetro não é um produto das medidas."},{id:"d",label:"2x + 2(x + 1) = 14",explanation:"Correto. São duas alturas e duas bases."}]),
  q(157,"Problema · idades","A idade do pai é o triplo da do filho. Daqui a 10 anos, será o dobro. Qual é a idade atual do pai?","Filho=x, pai=3x; daqui a 10 anos: 3x+10=2(x+10).","b",[
    {id:"a",label:"20 anos",explanation:"A idade atual não seria o triplo da do filho."},{id:"b",label:"30 anos",explanation:"Correto. O filho tem 10; daqui a 10 anos terão 20 e 40."},{id:"c",label:"40 anos",explanation:"Essa é a idade futura do pai."},{id:"d",label:"60 anos",explanation:"Não satisfaz a relação futura."}]),
  q(158,"Problema · frações","Marília recebeu 1/3 da mesada; a irmã recebeu 1/4 da sua. A irmã tem mesada R$20 menor e juntas receberam R$30. Qual é a mesada de Marília?","Se a mesada de Marília é x: x/3+(x−20)/4=30.","c",[
    {id:"a",label:"R$ 30",explanation:"Esse é o total recebido, não a mesada integral."},{id:"b",label:"R$ 40",explanation:"Um terço de 40 mais um quarto de 20 não totaliza 30."},{id:"c",label:"R$ 60",explanation:"Correto. 20 + 10 = 30; a irmã tem mesada de R$40."},{id:"d",label:"R$ 80",explanation:"As parcelas ultrapassariam R$30."}]),
  q(159,"Problema · acertos e erros","Ganha R$5 por acerto e perde R$3 por erro. Em 50 exercícios, ficou com R$130. Quantos acertou?","Acertos=x; erros=50−x: 5x−3(50−x)=130.","a",[
    {id:"a",label:"35",explanation:"Correto. 8x−150=130, então x=35."},{id:"b",label:"15",explanation:"Essa é a quantidade de erros."},{id:"c",label:"26",explanation:"Dividir 130 por 5 ignora as perdas."},{id:"d",label:"40",explanation:"40 acertos e 10 erros dariam R$170."}]),
  q(160,"Justificativa","Qual conclusão justifica completamente a solução de 4(x+1)=20?","Registre a operação, preserve a igualdade e confira a raiz.","d",[
    {id:"a",label:"x=4 porque passei o 4.",explanation:"Não explica a propriedade usada nem a conferência."},{id:"b",label:"x=4 porque 20−4=16.",explanation:"Faltam a distributiva, a divisão e a verificação."},{id:"c",label:"x=5 porque 20÷4=5.",explanation:"5 é o valor de x+1."},{id:"d",label:"Distribuí 4, subtraí 4 dos dois membros e dividi ambos por 4; x=4 e 4(4+1)=20.",explanation:"Correto. Procedimento e conferência estão explícitos."}]),
  q(161,"Conceitos","Qual item é uma sentença aberta?","Uma sentença aberta depende do valor de uma incógnita.","c",[
    {id:"a",label:"4x + 7",explanation:"É uma expressão: não apresenta igualdade nem desigualdade."},{id:"b",label:"18 − 5 = 13",explanation:"É uma sentença fechada verdadeira."},{id:"c",label:"3x + 2 = 20",explanation:"Correto. A verdade da igualdade depende do valor de x."},{id:"d",label:"9 > 12",explanation:"É uma sentença fechada falsa."}]),
  q(162,"Conceitos","Qual igualdade é uma identidade?","Uma identidade é verdadeira para todo valor permitido da variável.","a",[
    {id:"a",label:"2(x + 3) = 2x + 6",explanation:"Correto. A distributiva mostra que os dois membros são sempre equivalentes."},{id:"b",label:"4x + 1 = 13",explanation:"Só é verdadeira quando x=3."},{id:"c",label:"5x − 2 = 5x + 4",explanation:"Nunca é verdadeira: levaria a −2=4."},{id:"d",label:"x + 2 = 9",explanation:"Só é verdadeira quando x=7."}]),
  q(163,"Conjunto solução","Em U={0,1,2,3,4,5}, qual é o conjunto solução de 2x+1=9?","Resolva e depois confirme se o valor pertence ao universo.","d",[
    {id:"a",label:"S={3}",explanation:"2·3+1=7, não 9."},{id:"b",label:"S={5}",explanation:"2·5+1=11, não 9."},{id:"c",label:"S=∅",explanation:"Há uma solução pertencente ao universo."},{id:"d",label:"S={4}",explanation:"Correto. 2·4+1=9 e 4 pertence a U."}]),
  q(164,"Princípio da igualdade","Em 3x+5=20, qual ação preserva a igualdade?","Faça exatamente a mesma operação nos dois membros.","b",[
    {id:"a",label:"Subtrair 5 apenas do primeiro membro",explanation:"Isso desequilibra a igualdade."},{id:"b",label:"Subtrair 5 dos dois membros",explanation:"Correto. A mesma operação nos dois membros mantém a balança."},{id:"c",label:"Dividir apenas 3x por 3",explanation:"É preciso operar o membro inteiro e manter a igualdade."},{id:"d",label:"Trocar +5 por −5 sem alterar o outro membro",explanation:"A troca de sinal não acontece por mágica; ela representa uma operação nos dois lados."}]),
  q(165,"Equação direta","Resolva: 5x−7=18.","Some 7 aos dois membros e depois divida por 5.","c",[
    {id:"a",label:"x=11/5",explanation:"Você parece ter subtraído 7 de 18."},{id:"b",label:"x=25",explanation:"25 é o valor de 5x, não de x."},{id:"c",label:"x=5",explanation:"Correto. 5x=25, então x=5; 25−7=18."},{id:"d",label:"x=−5",explanation:"O sinal negativo não aparece ao aplicar as operações igualmente."}]),
  q(166,"Equação com distributiva","Resolva: 3(x+2)=x+14.","Distribua 3, reúna os termos com x e confira.","a",[
    {id:"a",label:"x=4",explanation:"Correto. 3x+6=x+14 → 2x=8 → x=4."},{id:"b",label:"x=6",explanation:"Você pode ter tratado 3(x+2) como 3x+2."},{id:"c",label:"x=8",explanation:"8 é o valor de 2x na penúltima etapa."},{id:"d",label:"x=10",explanation:"Não satisfaz a equação original."}]),
  q(167,"Historinha · diferença","Duas caixas têm juntas 30 lápis. A maior tem 6 lápis a mais que a menor. Quantos lápis há na menor?","Menor=x; maior=x+6; some as duas quantidades.","b",[
    {id:"a",label:"6",explanation:"6 é a diferença, não a quantidade da caixa menor."},{id:"b",label:"12",explanation:"Correto. x+(x+6)=30 → 2x=24 → x=12."},{id:"c",label:"18",explanation:"18 é a quantidade da caixa maior."},{id:"d",label:"24",explanation:"24 é o valor de 2x, não de x."}]),
  q(168,"Historinha · perímetro","Um retângulo tem largura x, comprimento x+3 e perímetro 26 cm. Quais são as medidas?","Perímetro é a soma de dois comprimentos e duas larguras.","d",[
    {id:"a",label:"3 cm e 10 cm",explanation:"A diferença é 7, não 3."},{id:"b",label:"4 cm e 7 cm",explanation:"O perímetro seria 22 cm."},{id:"c",label:"6 cm e 9 cm",explanation:"O perímetro seria 30 cm."},{id:"d",label:"5 cm e 8 cm",explanation:"Correto. 2x+2(x+3)=26 → 4x=20 → x=5."}]),
  q(169,"Historinha · tarifa","Uma corrida custa R$7 de bandeirada e R$3 por quilômetro. O total foi R$31. Quantos quilômetros foram percorridos?","Preço total = parte fixa + preço por quilômetro.","a",[
    {id:"a",label:"8 km",explanation:"Correto. 7+3x=31 → 3x=24 → x=8."},{id:"b",label:"10 km",explanation:"31÷3 ignora a parte fixa de R$7."},{id:"c",label:"12 km",explanation:"7+3·12=43, não 31."},{id:"d",label:"24 km",explanation:"24 é o valor de 3x antes da divisão."}]),
  q(170,"Historinha · idades","A mãe tem 4 vezes a idade da filha. Daqui a 8 anos terá o dobro da idade da filha. Qual é a idade atual da mãe?","Filha=x; mãe=4x; no futuro: 4x+8=2(x+8).","c",[
    {id:"a",label:"4 anos",explanation:"Essa é a idade atual da filha."},{id:"b",label:"8 anos",explanation:"Esse número é o intervalo de tempo."},{id:"c",label:"16 anos",explanation:"Correto. x=4, então a mãe tem 4x=16."},{id:"d",label:"24 anos",explanation:"Daqui a 8 anos a mãe terá 24, mas a pergunta pede a idade atual."}]),
  q(171,"Historinha · fração","Uma pessoa leu 2/5 de um livro e ainda faltam 18 páginas. Quantas páginas tem o livro?","Se o livro tem x páginas, restam 3/5 de x.","b",[
    {id:"a",label:"20",explanation:"3/5 de 20 é 12, não 18."},{id:"b",label:"30",explanation:"Correto. (3/5)x=18 → x=30."},{id:"c",label:"45",explanation:"18÷(2/5) usa a fração lida, não a fração restante."},{id:"d",label:"50",explanation:"3/5 de 50 é 30."}]),
  q(172,"Historinha · sistema","Em um cercado há galinhas e coelhos: 24 cabeças e 64 pernas. Quantos coelhos há?","g+c=24 e 2g+4c=64. Isole g=24−c e substitua.","d",[
    {id:"a",label:"4",explanation:"Com 4 coelhos haveria 56 pernas."},{id:"b",label:"12",explanation:"Com 12 coelhos haveria 72 pernas."},{id:"c",label:"16",explanation:"16 é a quantidade de galinhas."},{id:"d",label:"8",explanation:"Correto. 2(24−c)+4c=64 → 2c=16 → c=8."}]),
  q(173,"Historinha · sistema","Foram vendidos 120 ingressos: adulto a R$30 e infantil a R$15. A renda foi R$2700. Quantos ingressos adultos foram vendidos?","a+i=120 e 30a+15i=2700. Isole i=120−a.","a",[
    {id:"a",label:"60",explanation:"Correto. 30a+15(120−a)=2700 → 15a=900 → a=60."},{id:"b",label:"30",explanation:"Isso daria renda de R$2250."},{id:"c",label:"90",explanation:"Isso daria renda de R$3150."},{id:"d",label:"120",explanation:"Isso ignoraria os ingressos infantis e daria R$3600."}]),
  q(174,"Duas incógnitas","Ao isolar y em x+y=11, obtemos:","Subtraia x dos dois membros.","c",[
    {id:"a",label:"y=x−11",explanation:"A ordem da subtração foi invertida."},{id:"b",label:"y=11+x",explanation:"x deve ser subtraído, não somado."},{id:"c",label:"y=11−x",explanation:"Correto. x+y−x=11−x."},{id:"d",label:"y=11x",explanation:"Não há multiplicação na equação original."}]),
  q(175,"Sistema · substituição","Resolva por substituição: y=x+2 e 2x+y=11.","Substitua y por x+2 na segunda equação.","b",[
    {id:"a",label:"(2,5)",explanation:"2·2+5=9, não 11."},{id:"b",label:"(3,5)",explanation:"Correto. 2x+(x+2)=11 → x=3 e y=5."},{id:"c",label:"(5,3)",explanation:"A ordem é (x,y), e esse par não satisfaz y=x+2."},{id:"d",label:"(4,7)",explanation:"2·4+7=15."}]),
  q(176,"Sistema · substituição","Resolva: x=2y+1 e x+y=10.","Troque x por 2y+1 na segunda equação.","d",[
    {id:"a",label:"(3,7)",explanation:"A ordem foi invertida e x não é 2y+1."},{id:"b",label:"(5,5)",explanation:"5 não é igual a 2·5+1."},{id:"c",label:"(8,2)",explanation:"8+2=10, mas 8≠2·2+1."},{id:"d",label:"(7,3)",explanation:"Correto. (2y+1)+y=10 → y=3 e x=7."}]),
  q(177,"Sistema · substituição","Resolva: 3x+2y=18 e x=y+1.","Substitua x por y+1 na primeira equação.","a",[
    {id:"a",label:"(4,3)",explanation:"Correto. 3(y+1)+2y=18 → y=3 e x=4."},{id:"b",label:"(3,4)",explanation:"Esse par não satisfaz x=y+1."},{id:"c",label:"(5,2)",explanation:"3·5+2·2=19."},{id:"d",label:"(6,1)",explanation:"3·6+2=20."}]),
  q(178,"Sistema · substituição","Resolva: y=12−2x e x−y=3.","Substitua y por 12−2x na segunda equação.","c",[
    {id:"a",label:"(3,6)",explanation:"3−6=−3, não 3."},{id:"b",label:"(4,4)",explanation:"4−4=0."},{id:"c",label:"(5,2)",explanation:"Correto. x−(12−2x)=3 → 3x=15 → x=5 e y=2."},{id:"d",label:"(6,0)",explanation:"6−0=6, não 3."}]),
  q(179,"Método da substituição","Qual é o melhor primeiro passo no sistema y=4x−1 e 2x+y=14?","Uma incógnita já está isolada.","a",[
    {id:"a",label:"Substituir y por 4x−1 na segunda equação",explanation:"Correto. Isso produz uma equação apenas com x."},{id:"b",label:"Somar as duas equações",explanation:"A orientação deste conteúdo é usar substituição."},{id:"c",label:"Multiplicar a primeira equação por 2",explanation:"Não é necessário para substituir."},{id:"d",label:"Trocar y por 14",explanation:"14 é o segundo membro, não o valor de y."}]),
  q(180,"Conferência do sistema","O par (2,3) resolve o sistema x+y=5 e 2x−y=1?","Substitua o mesmo par nas duas equações.","b",[
    {id:"a",label:"Não, porque 2+3≠5",explanation:"Na verdade, 2+3=5."},{id:"b",label:"Sim, porque 2+3=5 e 2·2−3=1",explanation:"Correto. O par torna verdadeiras as duas equações."},{id:"c",label:"Sim, basta funcionar na primeira equação",explanation:"Uma solução de sistema precisa funcionar nas duas."},{id:"d",label:"Não, porque a ordem do par deveria ser (3,2)",explanation:"O par dado segue a ordem (x,y): x=2 e y=3."}]),
];

export const mathMockExams: MockExam[] = [
  {id:"math-ch9-concepts",title:"Quiz: Conceitos e Equações",shortTitle:"Conceitos e Equações",description:"Sentenças, identidades, conjunto solução e equações do 1º grau.",questionIds:[161,162,163,164,165,166],questionCount:6,minutes:12,level:"Focused"},
  {id:"math-ch9-stories",title:"Quiz: Decifrando Historinhas",shortTitle:"Historinhas",description:"Problemas que exigem interpretar, definir a incógnita e montar a equação.",questionIds:[167,168,169,170,171,172,173],questionCount:7,minutes:20,level:"Focused"},
  {id:"math-ch9-systems",title:"Quiz: Sistemas por Substituição",shortTitle:"Sistemas",description:"Duas incógnitas, substituição e conferência do par solução.",questionIds:[172,173,174,175,176,177,178,179,180],questionCount:9,minutes:22,level:"Focused"},
  {id:"math-ch9-complete",title:"Simulado · Capítulo 9",shortTitle:"Simulado Capítulo 9",description:"20 questões das páginas 170–197, com foco especial em modelagem e substituição.",questionIds:[161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180],questionCount:20,minutes:45,level:"Complete"},
];
