"use client";

import { useMemo, useState } from "react";
import { asset } from "./asset";

type Topic = "nominal" | "multimodal" | "commands";
type Props = { onBack: () => void; onGenerateFlashcards: (sourceId?: string) => void };
type Question = { topic: Topic; prompt: string; support?: string; options: string[]; answer: number; explanation: string };

const topics = [
  { id: "nominal" as const, number: "01", eyebrow: "SAS · P. 171–178", title: "Complemento nominal × adjunto adnominal", subtitle: "Núcleo, função e relação de sentido", image: asset("portuguese-cycle5/complemento-adjunto.webp"), deck: "portuguese-nominal" },
  { id: "multimodal" as const, number: "02", eyebrow: "LEITURA E INTERPRETAÇÃO", title: "Tirinha, charge, cartaz e propaganda", subtitle: "Tema, finalidade, explícito, implícito e multimodalidade", image: asset("portuguese-cycle5/leitura-multimodal.webp"), deck: "portuguese-reading" },
  { id: "commands" as const, number: "03", eyebrow: "GUIA DE ESTUDO · COMANDOS", title: "O que a questão está pedindo?", subtitle: "Identificar, explicar, interpretar, justificar e inferir", image: asset("portuguese-cycle5/verbos-comando.webp"), deck: "portuguese-reading" },
];

const questions: Question[] = [
  { topic:"nominal", prompt:"Em “A confiança nos colegas fortalece a equipe”, o termo destacado “nos colegas” é:", options:["adjunto adnominal","complemento nominal","objeto indireto","adjunto adverbial"], answer:1, explanation:"“Nos colegas” completa o sentido do substantivo abstrato “confiança” e indica o alvo da confiança." },
  { topic:"nominal", prompt:"Em “A confiança dos colegas fortalece a equipe”, “dos colegas” é:", options:["complemento nominal","adjunto adnominal","predicativo","objeto direto"], answer:1, explanation:"Os colegas são quem tem a confiança. A expressão indica agente/posse, relação típica de adjunto adnominal." },
  { topic:"nominal", prompt:"Qual expressão exerce função de complemento nominal?", options:["caderno de Lulu","amor de pai","necessidade de descanso","duas atividades"], answer:2, explanation:"“De descanso” completa o sentido de “necessidade”. Nas demais, há posse, agente/caracterização ou determinação numeral." },
  { topic:"nominal", prompt:"Em “Os dois alunos atentos concluíram a tarefa”, quantos adjuntos adnominais acompanham “alunos”?", options:["um","dois","três","quatro"], answer:2, explanation:"“Os” (artigo), “dois” (numeral) e “atentos” (adjetivo) determinam ou caracterizam o substantivo “alunos”." },
  { topic:"nominal", prompt:"Em “Ela estava favorável à mudança”, “à mudança” é complemento nominal porque:", options:["caracteriza um substantivo concreto","completa o sentido do adjetivo “favorável”","indica lugar","é agente da ação"], answer:1, explanation:"O complemento nominal também pode completar o sentido de adjetivos: favorável a quê? À mudança." },
  { topic:"nominal", prompt:"A preposição, sozinha, basta para classificar um termo como complemento nominal?", options:["Sim, sempre.","Sim, se for “de”.","Não; é preciso analisar núcleo, função e sentido.","Não; complemento nominal nunca tem preposição."], answer:2, explanation:"Essa é a armadilha principal: complemento nominal e adjunto adnominal podem ser preposicionados. A relação de sentido decide." },
  { topic:"nominal", prompt:"Compare: “amor de mãe” e “amor à mãe”. A classificação correta é:", options:["CN e CN","AA e AA","AA e CN","CN e AA"], answer:2, explanation:"“De mãe” indica origem/agente do amor: adjunto adnominal. “À mãe” indica o alvo do sentimento: complemento nominal." },
  { topic:"multimodal", prompt:"Uma tirinha termina com uma resposta inesperada que contradiz o primeiro quadrinho. Esse contraste constrói principalmente:", options:["uma definição científica","o efeito de humor","uma instrução","uma notícia"], answer:1, explanation:"Na tirinha, a quebra de expectativa entre os quadrinhos costuma produzir humor." },
  { topic:"multimodal", prompt:"Uma charge mostra um político oferecendo uma cenoura chamada “promessas” enquanto a população tenta alcançá-la. A imagem sugere:", options:["uma receita saudável","uma crítica a promessas usadas para convencer","uma campanha esportiva","um fato sem opinião"], answer:1, explanation:"A cenoura funciona como metáfora de algo prometido para conduzir ou manipular as pessoas." },
  { topic:"multimodal", prompt:"No cartaz “Economize água: cada gota faz a diferença”, a finalidade principal é:", options:["narrar uma aventura","divertir com uma piada","orientar e mobilizar o leitor","vender um produto"], answer:2, explanation:"O imperativo e a mensagem direta procuram modificar o comportamento do público." },
  { topic:"multimodal", prompt:"Em uma propaganda de tênis com o slogan “Energia para ir mais longe”, a expressão associa o produto a:", options:["cansaço e lentidão","desempenho e superação","silêncio e descanso","economia de água"], answer:1, explanation:"A escolha verbal cria uma promessa simbólica de energia, movimento e desempenho." },
  { topic:"multimodal", prompt:"Qual informação é implícita?", support:"Cartaz: “Biblioteca aberta até as 18h. Hoje, devolução sem multa.”", options:["A biblioteca fecha às 18h.","Hoje há uma condição especial para devolver livros atrasados.","O texto menciona devolução.","A palavra biblioteca aparece no cartaz."], answer:1, explanation:"A condição especial permite inferir que podem existir livros atrasados e que a campanha busca recuperá-los. As demais estão explícitas." },
  { topic:"multimodal", prompt:"Ao interpretar uma charge, por que o contexto de circulação é importante?", options:["Porque substitui completamente a imagem.","Porque a crítica costuma dialogar com um fato ou debate atual.","Porque toda charge é uma notícia neutra.","Porque dispensa a leitura das falas."], answer:1, explanation:"Sem reconhecer o acontecimento ou debate retomado, parte da crítica pode não ser compreendida." },
  { topic:"multimodal", prompt:"Qual resposta usa evidência de forma adequada?", options:["Achei engraçado, só isso.","É isso porque sim.","O anúncio quer persuadir, pois usa o imperativo “experimente” e destaca um benefício.","A imagem é bonita."], answer:2, explanation:"A resposta apresenta conclusão, pista concreta e explicação da relação." },
  { topic:"commands", prompt:"O verbo de comando “identifique” pede que o aluno:", options:["aponte o elemento solicitado","conte uma história","defenda uma opinião longa","reescreva todo o texto"], answer:0, explanation:"Identificar é reconhecer e apontar. Só explique se o enunciado também pedir explicação." },
  { topic:"commands", prompt:"Se a questão diz “justifique sua resposta”, o que não pode faltar?", options:["uma evidência ou argumento que sustente a resposta","uma resposta de uma palavra","uma opinião sem relação com o texto","a cópia integral do texto"], answer:0, explanation:"Justificar exige mostrar por que a resposta é válida, usando pistas, trechos ou relações lógicas." },
  { topic:"commands", prompt:"O comando “compare os dois anúncios” exige:", options:["apenas resumir o primeiro","apontar semelhanças e diferenças segundo critérios","escolher o mais bonito","copiar os slogans"], answer:1, explanation:"Comparar coloca os elementos em relação e evidencia aproximações e diferenças." },
  { topic:"commands", prompt:"“Infira a intenção do personagem” significa:", options:["localize uma frase literal","descubra pelas pistas o que não foi dito diretamente","classifique uma palavra","reescreva a fala"], answer:1, explanation:"Inferir é construir uma conclusão coerente a partir de pistas verbais e visuais." },
  { topic:"commands", prompt:"Qual resposta atende melhor ao comando “explique o efeito de humor”?", options:["É engraçado.","O humor surge porque a fala final contradiz a expectativa criada no primeiro quadrinho.","Gostei da tirinha.","Há três quadrinhos."], answer:1, explanation:"A alternativa explica o mecanismo do humor, em vez de apenas afirmar que ele existe." },
  { topic:"commands", prompt:"Antes de entregar uma resposta discursiva, a melhor revisão é:", options:["ver apenas se está longa","conferir comando, evidência, clareza e pontuação","apagar a justificativa","trocar toda frase por “sim” ou “não”"], answer:1, explanation:"A resposta precisa cumprir o verbo de comando, apoiar-se no texto e estar escrita de forma clara." },
];

export default function PortugueseCycle5({ onBack, onGenerateFlashcards }: Props) {
  const [active, setActive] = useState<Topic>("nominal");
  const [mode, setMode] = useState<"topic" | "exam">("topic");
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [checked, setChecked] = useState(false);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);
  const current = topics.find((item) => item.id === active)!;
  const queue = useMemo(() => mode === "exam" ? questions : questions.filter((item) => item.topic === active), [mode, active]);
  const question = queue[index];
  const reset = () => { setIndex(0); setSelected(null); setChecked(false); setScore(0); setFinished(false); };
  const choose = (topic: Topic) => { setActive(topic); setMode("topic"); reset(); requestAnimationFrame(() => document.getElementById("cycle5-topic")?.scrollIntoView({ behavior:"smooth" })); };
  const startExam = () => { setMode("exam"); reset(); requestAnimationFrame(() => document.getElementById("cycle5-quiz")?.scrollIntoView({ behavior:"smooth" })); };
  const check = () => { if (selected === null || checked) return; if (selected === question.answer) setScore((value) => value + 1); setChecked(true); };
  const next = () => { if (!checked) return; if (index === queue.length - 1) { setFinished(true); return; } setIndex((value) => value + 1); setSelected(null); setChecked(false); };

  return <div className="page history-page portuguese-page cycle5-page">
    <button className="back-button" onClick={onBack}>← Voltar para Português</button>
    <section className="history-hero portuguese-hero cycle5-hero"><div><span className="eyebrow light">PORTUGUÊS · CYCLE TEST 5</span><h1>Leia as pistas.<br/><em>Entenda as relações.</em></h1><p>Uma trilha autoral para estudar gramática e interpretação no padrão da avaliação.</p><div className="history-hero-meta"><span>3 módulos</span><span>SAS p. 171–178</span><span>3 infográficos</span><span>prova de 20 questões</span></div></div><div className="cycle5-hero-art" aria-hidden="true"><span>nome</span><b>+</b><strong>sentido</strong><i>?</i><em>pistas</em></div></section>
    <section className="history-source-note portuguese-source"><span>✓</span><div><strong>Roteiro alinhado ao guia de estudo</strong><p>Complemento nominal e adjunto adnominal · leitura de textos diversos · verbos de comando.</p></div></section>

    <section className="history-overview"><div className="section-heading"><div><span className="eyebrow coral">ROTA DE ESTUDO</span><h2>Aprenda, pratique e simule</h2></div><button className="portuguese-exam-cta" onClick={startExam}>Fazer prova completa · 20 questões →</button></div><div className="history-module-nav cycle5-nav">{topics.map((topic) => <button key={topic.id} className={active === topic.id ? "active" : ""} onClick={() => choose(topic.id)}><span>{topic.number}</span><i>{topic.id === "nominal" ? "Aa" : topic.id === "multimodal" ? "▣" : "?"}</i><small>{topic.eyebrow}</small><strong>{topic.title}</strong><em>{topic.subtitle}</em><b>Estudar →</b></button>)}</div></section>

    <section id="cycle5-topic" className="history-module-panel port-module"><header className="history-module-header"><div><span className="eyebrow light">MÓDULO {current.number} · {current.eyebrow}</span><h2>{current.title}</h2><p>{current.subtitle}</p></div><button onClick={() => onGenerateFlashcards(current.deck)}>✦ Flashcards deste assunto</button></header><Infographic src={current.image} title={current.title}/>{active === "nominal" && <NominalStudy/>}{active === "multimodal" && <MultimodalStudy/>}{active === "commands" && <CommandsStudy/>}<footer className="history-module-footer"><div><small>MÉTODO DA LULU</small><strong>Localize → relacione → explique com uma pista → confira o comando.</strong></div><button onClick={() => { setMode("topic"); reset(); document.getElementById("cycle5-quiz")?.scrollIntoView({behavior:"smooth"}); }}>Fazer quiz do módulo →</button></footer></section>

    <section id="cycle5-quiz" className="history-quiz portuguese-quiz"><header><div><span className="eyebrow coral">{mode === "exam" ? "PROVA SIMULADA · CYCLE TEST 5" : `QUIZ · ${current.title}`}</span><h2>{mode === "exam" ? "20 questões comentadas" : `${queue.length} questões para fixar`}</h2></div><div className="history-quiz-progress"><span>{finished ? "fim" : `${index + 1}/${queue.length}`}</span><i><b style={{width:`${finished ? 100 : ((index + 1) / queue.length) * 100}%`}}/></i></div></header>{finished ? <div className="history-quiz-result"><span>{score}/{queue.length}</span><h3>{score / queue.length >= .8 ? "Domínio alcançado!" : score / queue.length >= .6 ? "Boa base — revise os comentários." : "Volte aos módulos e tente outra vez."}</h3><p>{mode === "exam" ? "A prova misturou gramática, leitura e verbos de comando." : "Leia as explicações e refaça as questões difíceis."}</p><div className="quiz-result-actions"><button onClick={reset}>Refazer</button>{mode === "topic" && <button onClick={startExam}>Ir para a prova completa</button>}</div></div> : <div className="history-question"><small>{mode === "exam" ? `QUESTÃO ${index + 1} · ${topics.find((item) => item.id === question.topic)?.title}` : `QUESTÃO ${index + 1}`}</small><h3>{question.prompt}</h3>{question.support && <blockquote className="cycle5-support">{question.support}</blockquote>}<div>{question.options.map((option, optionIndex) => <button key={option} className={`${selected === optionIndex ? "selected" : ""} ${checked && optionIndex === question.answer ? "correct" : ""} ${checked && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} disabled={checked} onClick={() => setSelected(optionIndex)}><b>{String.fromCharCode(65 + optionIndex)}</b><span>{option}</span></button>)}</div>{checked && <aside className={selected === question.answer ? "correct" : "wrong"}><strong>{selected === question.answer ? "✓ Acertou" : "↗ Ajuste o raciocínio"}</strong><p>{question.explanation}</p></aside>}<footer><button disabled={selected === null || checked} onClick={check}>Conferir resposta</button><button disabled={!checked} onClick={next}>{index === queue.length - 1 ? "Ver resultado" : "Próxima questão →"}</button></footer></div>}</section>
  </div>;
}

function Infographic({src,title}:{src:string;title:string}) { return <figure className="history-infographic"><a href={src} target="_blank" rel="noreferrer"><img src={src} alt={`Infográfico: ${title}`} loading="lazy"/></a><figcaption><div><small>INFOGRÁFICO PARA REVISÃO</small><strong>Toque para abrir em tamanho completo</strong></div><a href={src} download>Baixar ↓</a></figcaption></figure>; }

function NominalStudy(){return <div className="history-module-body"><section className="cycle5-decision"><b>1</b><span>Ache o núcleo</span><i>→</i><b>2</b><span>Veja o termo ligado</span><i>→</i><b>3</b><span>Analise a relação</span><i>→</i><b>4</b><span>Classifique e justifique</span></section><section className="history-two-columns"><article className="history-card cycle5-cn"><header><span>CN</span><div><small>COMPLEMENTO NOMINAL</small><h3>Completa um sentido</h3></div></header><p>Liga-se a <b>substantivo abstrato, adjetivo ou advérbio</b>, geralmente com preposição. Costuma indicar o <b>alvo/paciente</b>.</p><div className="history-formula">respeito <u>aos professores</u> · favorável <u>à mudança</u></div></article><article className="history-card cycle5-aa"><header><span>AA</span><div><small>ADJUNTO ADNOMINAL</small><h3>Determina ou caracteriza</h3></div></header><p>Acompanha um <b>substantivo</b>. Pode ser artigo, adjetivo, pronome, numeral ou locução adjetiva. Costuma indicar <b>agente, posse ou característica</b>.</p><div className="history-formula"><u>os dois</u> alunos <u>atentos</u> · amor <u>de mãe</u></div></article></section><section className="port-three"><article><small>ALVO</small><h3>amor à família</h3><p>A família recebe o sentimento → <b>CN</b>.</p></article><article><small>AGENTE/ORIGEM</small><h3>amor de mãe</h3><p>A mãe sente/origina o amor → <b>AA</b>.</p></article><article><small>ARMADILHA</small><h3>Há preposição nos dois</h3><p>Não classifique pela preposição. <b>O sentido decide.</b></p></article></section><aside className="history-source-tip"><span>!</span><div><small>JUSTIFICATIVA QUE FUNCIONA</small><p>“É complemento nominal porque completa o sentido do nome e indica o alvo.” ou “É adjunto adnominal porque caracteriza o substantivo e indica agente/posse.”</p></div></aside></div>}

function MultimodalStudy(){return <div className="history-module-body"><section className="cycle5-reading-route"><article><b>1</b><strong>Varredura</strong><p>Título, gênero, fonte, imagens, cores, balões, gestos.</p></article><article><b>2</b><strong>Essencial</strong><p>Tema, finalidade, público e ideia principal.</p></article><article><b>3</b><strong>Pistas</strong><p>Separe o explícito do que precisa ser inferido.</p></article><article><b>4</b><strong>Resposta</strong><p>Conclusão + pista + explicação da relação.</p></article></section><section className="port-four cycle5-genres"><article><b>▤</b><h3>Tirinha</h3><p>Sequência, personagens, balões e quebra de expectativa.</p></article><article><b>✎</b><h3>Charge</h3><p>Crítica, humor e ligação com um fato ou debate atual.</p></article><article><b>▣</b><h3>Cartaz</h3><p>Mensagem rápida, hierarquia visual e chamada para ação.</p></article><article><b>◉</b><h3>Propaganda</h3><p>Persuasão, público-alvo, slogan e promessa simbólica.</p></article></section><section className="history-two-columns"><article className="history-card"><header><span>TXT</span><div><small>EXPLÍCITO</small><h3>Está declarado</h3></div></header><p>Pode ser localizado no texto ou na imagem. Ainda assim, responda com frase completa quando a questão for discursiva.</p></article><article className="history-card"><header><span>?</span><div><small>IMPLÍCITO</small><h3>É construído pelas pistas</h3></div></header><p>Inferir não é inventar: combine uma pista verbal ou visual com um raciocínio coerente.</p><div className="history-formula">pista + contexto + relação lógica = inferência</div></article></section></div>}

function CommandsStudy(){const commands=[["IDENTIFICAR","apontar o elemento"],["EXPLICAR","mostrar motivo e relação"],["INTERPRETAR","construir o sentido"],["ANALISAR","examinar partes e conexões"],["JUSTIFICAR","sustentar com evidência"],["COMPARAR","semelhanças e diferenças"],["INFERIR","concluir pelas pistas"],["CLASSIFICAR","aplicar critérios"]];return <div className="history-module-body"><section className="port-command-grid">{commands.map(([verb,action])=><article key={verb}><b>{verb}</b><span>{action}</span></article>)}</section><section className="port-answer-formula"><small>RESPOSTA FORTE</small><strong>resposta direta</strong><i>＋</i><strong>pista ou trecho</strong><i>＋</i><strong>explicação</strong></section><section className="history-two-columns"><article className="history-card"><header><span>✓</span><div><small>ANTES DE ESCREVER</small><h3>Circule o comando</h3></div></header><ol className="port-list"><li>O que exatamente devo fazer?</li><li>Quantos elementos a questão pede?</li><li>Preciso citar evidência ou comparar?</li><li>A resposta deve ser objetiva ou desenvolvida?</li></ol></article><article className="history-card"><header><span>↻</span><div><small>ANTES DE ENTREGAR</small><h3>Revisão de 20 segundos</h3></div></header><ol className="port-list"><li>Respondi ao verbo de comando?</li><li>Minha evidência realmente prova a resposta?</li><li>Expliquei a relação ou apenas copiei?</li><li>Usei frase completa e pontuação?</li></ol></article></section></div>}
