"use client";

import { useMemo, useState } from "react";
import { asset } from "./asset";

type ModuleId = "predicates" | "transitivity" | "pronouns" | "reading";
type Props = { onBack: () => void; onGenerateFlashcards: (sourceId?: string) => void };
type Question = { topic: ModuleId; question: string; options: string[]; answer: number; explanation: string };

const modules: Array<{ id: ModuleId; number: string; pages: string; title: string; subtitle: string; deck: string; infographic: string }> = [
  { id: "predicates", number: "01", pages: "SAS · P. 101–107", title: "Predicados e predicativo do sujeito", subtitle: "Núcleos, verbos significativos e verbos de ligação", deck: "portuguese-predicates", infographic: asset("portuguese/portugues-01-predicados.webp") },
  { id: "transitivity", number: "02", pages: "SAS · P. 124–133", title: "Transitividade e predicativo do objeto", subtitle: "VI, VTD, VTI, VTDI, objetos e sentidos no contexto", deck: "portuguese-transitivity", infographic: asset("portuguese/portugues-02-transitividade.webp") },
  { id: "pronouns", number: "03", pages: "SAS · P. 152–157", title: "Colocação pronominal", subtitle: "Próclise, ênclise, mesóclise e função dos pronomes", deck: "portuguese-pronouns", infographic: asset("portuguese/portugues-03-colocacao-pronominal.webp") },
  { id: "reading", number: "04", pages: "GUIA DE ESTUDO · LEITURA", title: "Interpretação e verbos de comando", subtitle: "Explícito, implícito, multimodalidade e respostas completas", deck: "portuguese-reading", infographic: asset("portuguese/portugues-04-interpretacao.webp") },
];

const questions: Question[] = [
  { topic:"predicates", question:"Em “Os estudantes resolveram o desafio”, qual é o tipo de predicado?", options:["Nominal","Verbal","Verbo-nominal","Sem predicado"], answer:1, explanation:"“Resolveram” é verbo significativo e núcleo do predicado; a informação central é uma ação." },
  { topic:"predicates", question:"Em “A sala permaneceu silenciosa”, qual é o núcleo do predicado?", options:["sala","permaneceu","silenciosa","a"], answer:2, explanation:"O verbo liga o sujeito à característica; “silenciosa” é predicativo do sujeito e núcleo do predicado nominal." },
  { topic:"predicates", question:"Em “Os atletas chegaram cansados”, temos:", options:["predicado verbal","predicado nominal","predicado verbo-nominal","oração sem sujeito"], answer:2, explanation:"Há dois núcleos: “chegaram” indica ação e “cansados” atribui estado ao sujeito." },
  { topic:"predicates", question:"Em qual frase “ficou” funciona como verbo de ligação?", options:["Lulu ficou em casa.","Lulu ficou preocupada.","Lulu ficou ali.","Lulu ficou na biblioteca."], answer:1, explanation:"Só em “ficou preocupada” o verbo liga Lulu a uma característica. Nas outras, indica permanência/localização." },
  { topic:"predicates", question:"O predicativo do sujeito é o termo que:", options:["pratica sempre uma ação","completa um nome","atribui estado ou característica ao sujeito","indica apenas lugar"], answer:2, explanation:"Ele caracteriza ou identifica o sujeito e pode ser adjetivo, locução, substantivo, pronome ou numeral." },
  { topic:"transitivity", question:"Em “Ela precisa de ajuda”, o verbo é:", options:["VI","VTD","VTI","VTDI"], answer:2, explanation:"“Precisar”, nesse sentido, exige complemento com a preposição “de”: de ajuda, objeto indireto." },
  { topic:"transitivity", question:"Em “O professor entregou a atividade aos alunos”, os complementos são:", options:["dois objetos diretos","OD “a atividade” e OI “aos alunos”","OI “a atividade” e OD “aos alunos”","dois predicativos"], answer:1, explanation:"Quem entrega, entrega algo a alguém: “a atividade” é OD; “aos alunos” é OI." },
  { topic:"transitivity", question:"Em “A plateia considerou o espetáculo emocionante”, “emocionante” é:", options:["predicativo do objeto","predicativo do sujeito","objeto indireto","adjunto de lugar"], answer:0, explanation:"A característica “emocionante” é atribuída ao objeto direto “o espetáculo”." },
  { topic:"transitivity", question:"Por que “Ontem sonhei com você” e “Faz anos que não sonho” podem ter classificações diferentes?", options:["O sujeito mudou.","A transitividade depende do sentido e da construção no contexto.","Todo verbo é sempre transitivo.","A preposição nunca importa."], answer:1, explanation:"No primeiro caso, “sonhar com” pede complemento; no segundo, “sonho” apresenta sentido completo." },
  { topic:"transitivity", question:"Em “O bebê chorou durante a noite”, “durante a noite” é:", options:["objeto direto","objeto indireto","informação circunstancial, não complemento obrigatório","predicativo do objeto"], answer:2, explanation:"“Chorou” já tem sentido completo; a expressão apenas acrescenta circunstância de tempo." },
  { topic:"pronouns", question:"Qual frase segue a norma-padrão por causa da palavra atrativa?", options:["Não avisaram-me.","Não me avisaram.","Não avisar-me-ão.","Me não avisaram."], answer:1, explanation:"A palavra negativa “não” atrai o pronome para antes do verbo: próclise." },
  { topic:"pronouns", question:"Qual frase exige ênclise na norma-padrão?", options:["Sempre me ajudam.","Quem te chamou?","Entregaram-me os documentos.","Não se preocupe."], answer:2, explanation:"Com o verbo iniciando a oração e sem palavra atrativa, o pronome vem depois, unido por hífen." },
  { topic:"pronouns", question:"Quando a mesóclise é empregada?", options:["Em qualquer verbo no passado","No futuro do presente ou do pretérito, sem palavra atrativa","Depois de toda negação","Somente na linguagem informal"], answer:1, explanation:"Ex.: “Entregar-lhe-ei”. É uma construção formal e pouco comum na fala atual." },
  { topic:"pronouns", question:"Qual pronome oblíquo funciona somente como objeto indireto?", options:["o","a","lhe","os"], answer:2, explanation:"“Lhe/lhes” substituem objeto indireto; “o/a/os/as” substituem objeto direto." },
  { topic:"pronouns", question:"Em qual opção a vírgula muda a atração do pronome?", options:["Hoje me contaram / Hoje, contaram-me","Não me disseram / Não, me disseram","Quem te chamou / Quem, te chamou","Nunca se sabe / Nunca, se sabe"], answer:0, explanation:"O adverbio não isolado atrai o pronome; isolado por vírgula, deixa de exercer essa atração." },
  { topic:"reading", question:"O comando “justifique” pede que você:", options:["copie qualquer frase","dê uma opinião sem explicar","apresente uma resposta sustentada por evidência e raciocínio","liste palavras difíceis"], answer:2, explanation:"Justificar é defender a resposta com trecho, pista, dado ou relação lógica do texto." },
  { topic:"reading", question:"Uma informação implícita é aquela que:", options:["aparece escrita literalmente","pode ser inferida a partir de pistas","não tem relação com o texto","depende apenas da opinião do leitor"], answer:1, explanation:"A inferência combina pistas do texto com raciocínio, sem inventar informação." },
  { topic:"reading", question:"Ao ler uma charge, o que deve ser analisado além das falas?", options:["Apenas o número de letras","Título, fonte, imagens, gestos, símbolos e relação entre linguagens","Somente a cor do papel","A biografia completa do leitor"], answer:1, explanation:"Textos multimodais constroem sentido pela interação entre palavras e elementos visuais." },
  { topic:"reading", question:"Qual fórmula produz uma resposta interpretativa mais forte?", options:["opinião + ponto final","resposta + pista/trecho + explicação da relação","cópia integral do texto","sim ou não"], answer:1, explanation:"A evidência precisa ser conectada à conclusão; só copiar não demonstra compreensão." },
  { topic:"reading", question:"Antes de responder uma questão, o primeiro cuidado deve ser:", options:["ignorar o verbo de comando","identificar exatamente o que o comando pede","buscar a maior alternativa","responder de memória"], answer:1, explanation:"“Identificar”, “explicar”, “comparar” e “inferir” exigem operações diferentes." },
];

export default function PortugueseReview({ onBack, onGenerateFlashcards }: Props) {
  const [active, setActive] = useState<ModuleId>("predicates");
  const [mode, setMode] = useState<"topic" | "exam">("topic");
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [checked, setChecked] = useState(false);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);
  const current = modules.find((item) => item.id === active)!;
  const queue = useMemo(() => mode === "exam" ? questions : questions.filter((item) => item.topic === active), [mode, active]);
  const question = queue[index];

  const chooseModule = (id: ModuleId) => { setActive(id); setMode("topic"); restart(); requestAnimationFrame(() => document.getElementById("portuguese-module")?.scrollIntoView({ behavior:"smooth", block:"start" })); };
  function restart() { setIndex(0); setSelected(null); setChecked(false); setScore(0); setFinished(false); }
  const startExam = () => { setMode("exam"); restart(); requestAnimationFrame(() => document.getElementById("portuguese-quiz")?.scrollIntoView({ behavior:"smooth" })); };
  const check = () => { if (selected === null || checked) return; if (selected === question.answer) setScore((value) => value + 1); setChecked(true); };
  const next = () => { if (!checked) return; if (index === queue.length - 1) { setFinished(true); return; } setIndex((value) => value + 1); setSelected(null); setChecked(false); };

  return <div className="page history-page portuguese-page">
    <button className="back-button" onClick={onBack}>← Voltar para trimestres</button>
    <section className="history-hero portuguese-hero"><div><span className="eyebrow light">PORTUGUÊS · REVISÃO</span><h1>Entender a língua,<br/><em>não decorar etiquetas.</em></h1><p>Revisão detalhada a partir do guia de estudo e da leitura das páginas indicadas no livro oficial do SAS.</p><div className="history-hero-meta"><span>4 assuntos</span><span>23 páginas do SAS</span><span>4 quizzes</span><span>prova de 20 questões</span></div></div><div className="portuguese-hero-art" aria-hidden="true"><b>oração</b><span>sujeito</span><i>predicado</i><em>me · te · se</em><strong>?</strong></div></section>
    <section className="history-source-note portuguese-source"><span>✓</span><div><strong>Conteúdo conferido no guia e no livro digital oficial do SAS</strong><p>Predicados: 101–107 · Transitividade: 124–133 · Colocação pronominal: 152–157 · Interpretação e comandos do Study Guide</p></div></section>

    <section className="history-overview"><div className="section-heading"><div><span className="eyebrow coral">ROTA DE ESTUDO</span><h2>Um assunto de cada vez</h2></div><button className="portuguese-exam-cta" onClick={startExam}>Fazer prova completa · 20 questões →</button></div><div className="history-module-nav">{modules.map((module) => <button key={module.id} className={active === module.id ? "active" : ""} onClick={() => chooseModule(module.id)}><span>{module.number}</span><i>{module.id === "predicates" ? "Aa" : module.id === "transitivity" ? "→" : module.id === "pronouns" ? "↔" : "?"}</i><small>{module.pages}</small><strong>{module.title}</strong><em>{module.subtitle}</em><b>Estudar →</b></button>)}</div></section>

    <section id="portuguese-module" className={`history-module-panel port-module port-${active}`}><header className="history-module-header"><div><span className="eyebrow light">MÓDULO {current.number} · {current.pages}</span><h2>{current.title}</h2><p>{current.subtitle}</p></div><button onClick={() => onGenerateFlashcards(current.deck)}>✦ Flashcards deste assunto</button></header><Infographic src={current.infographic} title={current.title}/>{active === "predicates" && <Predicates/>}{active === "transitivity" && <Transitivity/>}{active === "pronouns" && <Pronouns/>}{active === "reading" && <Reading/>}<footer className="history-module-footer"><div><small>MÉTODO LULU</small><strong>Defina → localize no exemplo → explique por que é essa classificação.</strong></div><button onClick={() => { setMode("topic"); restart(); document.getElementById("portuguese-quiz")?.scrollIntoView({behavior:"smooth"}); }}>Fazer quiz do assunto →</button></footer></section>

    <section id="portuguese-quiz" className="history-quiz portuguese-quiz"><header><div><span className="eyebrow coral">{mode === "exam" ? "PROVA COMPLETA" : `QUIZ · ${current.title}`}</span><h2>{mode === "exam" ? "20 questões comentadas" : "5 questões para fixar"}</h2></div><div className="history-quiz-progress"><span>{finished ? "fim" : `${index + 1}/${queue.length}`}</span><i><b style={{width:`${finished ? 100 : ((index + 1) / queue.length) * 100}%`}}/></i></div></header>{finished ? <div className="history-quiz-result"><span>{score}/{queue.length}</span><h3>{score / queue.length >= .8 ? "Excelente domínio!" : score / queue.length >= .6 ? "Boa base — revise os comentários." : "Volte aos módulos e tente outra vez."}</h3><p>{mode === "exam" ? "A prova misturou gramática, análise e interpretação." : "Use a explicação de cada questão para ajustar o raciocínio."}</p><div className="quiz-result-actions"><button onClick={restart}>Refazer</button>{mode === "topic" && <button onClick={startExam}>Ir para prova completa</button>}</div></div> : <div className="history-question"><small>{mode === "exam" ? `PROVA · ${modules.find((m) => m.id === question.topic)?.title}` : `QUESTÃO ${index + 1}`}</small><h3>{question.question}</h3><div>{question.options.map((option, optionIndex) => <button key={option} className={`${selected === optionIndex ? "selected" : ""} ${checked && optionIndex === question.answer ? "correct" : ""} ${checked && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} disabled={checked} onClick={() => setSelected(optionIndex)}><b>{String.fromCharCode(65 + optionIndex)}</b><span>{option}</span></button>)}</div>{checked && <aside className={selected === question.answer ? "correct" : "wrong"}><strong>{selected === question.answer ? "✓ Acertou" : "↗ Ajuste o raciocínio"}</strong><p>{question.explanation}</p></aside>}<footer><button disabled={selected === null || checked} onClick={check}>Conferir resposta</button><button disabled={!checked} onClick={next}>{index === queue.length - 1 ? "Ver resultado" : "Próxima questão →"}</button></footer></div>}</section>
  </div>;
}

function Infographic({src,title}:{src:string;title:string}) { return <figure className="history-infographic"><a href={src} target="_blank" rel="noreferrer"><img src={src} alt={`Infográfico detalhado: ${title}`} loading="lazy"/></a><figcaption><div><small>INFOGRÁFICO DETALHADO</small><strong>Toque para abrir e estudar em tamanho completo</strong></div><a href={src} target="_blank" rel="noreferrer">Ampliar ↗</a></figcaption></figure> }

function Predicates(){return <div className="history-module-body"><section className="port-rule"><b>1</b><span>Localize o sujeito</span><i>→</i><b>2</b><span>Separe o predicado</span><i>→</i><b>3</b><span>Encontre o(s) núcleo(s)</span></section><section className="port-three"><article><small>PREDICADO VERBAL</small><h3>Ação ou acontecimento</h3><p>Núcleo = <b>verbo significativo</b>. Ele expressa ação, fenômeno, desejo ou atividade mental.</p><code>Os alunos <mark>resolveram</mark> o exercício.</code></article><article><small>PREDICADO NOMINAL</small><h3>Estado ou característica</h3><p>Núcleo = <b>nome/predicativo</b>. O verbo de ligação apenas conecta o sujeito à qualidade.</p><code>A turma estava <mark>animada</mark>.</code></article><article><small>VERBO-NOMINAL</small><h3>Ação + característica</h3><p>Dois núcleos: verbo significativo e nome que caracteriza sujeito ou objeto.</p><code>A turma <mark>saiu</mark> <mark>animada</mark>.</code></article></section><section className="history-two-columns"><article className="history-card"><header><span>VL</span><div><small>VERBOS DE LIGAÇÃO</small><h3>O contexto decide</h3></div></header><p><b>ser, estar, parecer, permanecer, continuar, ficar, tornar-se</b> podem ligar o sujeito a estado/qualidade. Mas não basta decorar a lista.</p><div className="port-contrast"><span>Ela <b>ficou cansada</b>.<small>ligação + característica</small></span><span>Ela <b>ficou em casa</b>.<small>permanência/localização</small></span></div></article><article className="history-card"><header><span>PS</span><div><small>PREDICATIVO DO SUJEITO</small><h3>De quem é a característica?</h3></div></header><p>Termo que atribui estado, qualidade ou identificação ao sujeito. Pode ser adjetivo, locução adjetiva, substantivo, pronome ou numeral.</p><div className="history-formula">As meninas chegaram contentes. → “contentes” caracteriza “as meninas”.</div></article></section><aside className="history-source-tip"><span>!</span><div><small>PEGADINHA DO SAS</small><p><b>“Andou alegre”</b>: ligação; <b>“andou muito”</b>: ação. <b>“Continuou silencioso”</b>: ligação; <b>“continuou a tarefa”</b>: ação.</p></div></aside></div>}

function Transitivity(){return <div className="history-module-body"><section className="port-question-rule"><strong>O verbo tem sentido completo?</strong><span>sim → intransitivo</span><span>não → procure o complemento e a preposição exigida</span></section><section className="port-four"><article><b>VI</b><h3>Intransitivo</h3><p>Não exige complemento.</p><code>O bebê nasceu.</code></article><article><b>VTD</b><h3>Transitivo direto</h3><p>Exige OD, sem preposição obrigatória.</p><code>Li o manual.</code></article><article><b>VTI</b><h3>Transitivo indireto</h3><p>Exige OI, com preposição.</p><code>Preciso de ajuda.</code></article><article><b>VTDI</b><h3>Direto e indireto</h3><p>Exige OD + OI.</p><code>Entreguei a prova à professora.</code></article></section><section className="history-two-columns"><article className="history-card"><header><span>OD</span><div><small>OBJETOS</small><h3>Pergunte ao verbo</h3></div></header><p><b>OD:</b> o quê? quem? sem preposição exigida.<br/><b>OI:</b> de quê? em quê? a quem? com preposição exigida.</p><div className="history-formula">Ela enviou <u>uma mensagem</u> <u>ao amigo</u>. → OD + OI</div></article><article className="history-card"><header><span>PO</span><div><small>PREDICATIVO DO OBJETO</small><h3>Característica atribuída ao objeto</h3></div></header><p>Em “Os colegas consideraram <b>Pedro inteligente</b>”, Pedro é OD e inteligente é predicativo do objeto.</p><div className="port-contrast"><span>Pedro estava <b>inteligente</b>.<small>predicativo do sujeito</small></span><span>Consideraram Pedro <b>inteligente</b>.<small>predicativo do objeto</small></span></div></article></section><aside className="history-source-tip"><span>↻</span><div><small>O SENTIDO MUDA A CLASSIFICAÇÃO</small><p><b>“Sonhei com você”</b> = VTI. <b>“Faz anos que não sonho”</b> = VI. Expressões de tempo, lugar ou modo podem ser circunstâncias, não complementos obrigatórios.</p></div></aside></div>}

function Pronouns(){return <div className="history-module-body"><section className="port-pronoun-strip"><span>me</span><span>te</span><span>se</span><span>o/a</span><span>lhe</span><span>nos</span><span>vos</span><span>os/as</span><span>lhes</span></section><section className="port-three"><article><small>PRÓCLISE · ANTES</small><h3>Não <mark>me</mark> avisaram.</h3><p>Obrigatória com palavra atrativa: negação; advérbio sem vírgula; pronomes relativo, indefinido ou demonstrativo; interrogativa/exclamativa; conjunção subordinativa.</p></article><article><small>ÊNCLISE · DEPOIS</small><h3>Avisaram-<mark>me</mark>.</h3><p>Usada quando o verbo inicia a oração ou vem depois de pausa, sem palavra atrativa. O pronome liga-se por hífen.</p></article><article><small>MESÓCLISE · NO MEIO</small><h3>Entregar-<mark>lhe</mark>-ei.</h3><p>Futuro do presente ou futuro do pretérito, sem palavra atrativa. É formal e hoje pouco frequente.</p></article></section><section className="history-two-columns"><article className="history-card"><header><span>?</span><div><small>FLUXO DE DECISÃO</small><h3>Como escolher</h3></div></header><ol className="port-list"><li>Há palavra atrativa? → <b>próclise</b>.</li><li>É futuro e não há atrator? → <b>mesóclise</b>.</li><li>O verbo inicia a oração? → <b>ênclise</b>.</li><li>Sem atrator e verbo não inicial? A posição pode ser facultativa em certos casos.</li></ol></article><article className="history-card"><header><span>OD</span><div><small>FUNÇÃO E ACENTO</small><h3>Não basta olhar a posição</h3></div></header><p><b>o/a/os/as</b> = somente OD · <b>lhe/lhes</b> = somente OI · <b>me/te/nos/vos/se</b> = OD ou OI.</p><div className="history-formula">entregá-la · vê-lo · construí-lo</div><p>Na fala brasileira, “Me avise” é comum; no início da oração, a norma-padrão prefere <b>“Avise-me”</b>.</p></article></section></div>}

function Reading(){return <div className="history-module-body"><section className="port-rule"><b>1</b><span>Leia o comando</span><i>→</i><b>2</b><span>Localize pistas</span><i>→</i><b>3</b><span>Relacione</span><i>→</i><b>4</b><span>Justifique</span></section><section className="history-two-columns"><article className="history-card"><header><span>TXT</span><div><small>CAMADAS DO TEXTO</small><h3>Explícito × implícito</h3></div></header><p><b>Explícito:</b> está declarado e pode ser localizado.<br/><b>Implícito:</b> é inferido por pistas, relações e contexto — sem inventar.</p><div className="history-formula">inferência = pista textual + raciocínio coerente</div></article><article className="history-card"><header><span>▣</span><div><small>MULTIMODALIDADE</small><h3>Palavra e imagem trabalham juntas</h3></div></header><p>Observe título, gênero, fonte, autoria, público, finalidade, imagens, cores, tamanho das letras, símbolos, balões, gestos e expressões. Pergunte o que cada linguagem acrescenta.</p></article></section><section className="port-command-grid"><article><b>identificar · localizar</b><span>encontrar a informação pedida</span></article><article><b>explicar · interpretar</b><span>mostrar sentido e relações</span></article><article><b>analisar · relacionar</b><span>examinar partes e conexões</span></article><article><b>justificar</b><span>sustentar com evidência</span></article><article><b>comparar · diferenciar</b><span>semelhanças e diferenças</span></article><article><b>classificar</b><span>aplicar critérios estudados</span></article><article><b>inferir</b><span>concluir a partir de pistas</span></article><article><b>reescrever · produzir</b><span>transformar ou criar conforme regras</span></article></section><section className="port-answer-formula"><small>RESPOSTA FORTE</small><strong>resposta direta</strong><i>＋</i><strong>trecho ou pista</strong><i>＋</i><strong>explicação da relação</strong></section><aside className="history-source-tip"><span>✓</span><div><small>CHECKLIST FINAL</small><p>Respondi ao verbo de comando? Usei o texto? Expliquei a evidência? Evitei opinião solta, cópia sem análise e respostas apenas “sim/não”?</p></div></aside></div>}
